searchworks:
  api:
    prefix: "http://searchworks.stanford.edu/view/"
    suffix: ".mobile"
  link:
    prefix: "http://searchworks.stanford.edu/view/"
purl:
  link:
    prefix: "http://purl.stanford.edu/"
feature_flags:
  themes: true
  bibliography_resource: true
  search_across: true
  home_page_navbar: true
