searchworks:
  api:
    prefix: "http://searchworks.stanford.edu/view/"
    suffix: ".mobile"
  link:
    prefix: "http://searchworks.stanford.edu/view/"
purl:
  link:
    prefix: "http://purl.stanford.edu/"
feature_flags:
  themes: true
  bibliography_resource: true
  test-flag-exhibit-slug:
    test_thing: true
    bibliography_resource: false
    index_related_content: true
    add_resource_type_index_field: true
    mirador_options:
      sidePanelOptions:
        tocTabAvailable: true 
        layersTabAvailable: false 
        searchTabAvailable: true 
      windowSettings:
        sidePanel: true 
        sidePanelVisible: true

