searchworks:
  api:
    prefix: "http://searchworks.stanford.edu/view/"
    suffix: ".mobile"
  link:
    prefix: "http://searchworks.stanford.edu/view/"
purl:
  link:
    prefix: "http://purl.stanford.edu/"
feature_flags:
  themes: true
  bibliography_resource: true
  search_across: true
  test-flag-exhibit-slug:
    test_thing: true
    bibliography_resource: false
    index_related_content: true
    add_resource_type_index_field: true
    uat_embed: true
